#!/bin/bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
export PYTHONPATH="${ROOT_DIR}/python${PYTHONPATH:+:${PYTHONPATH}}"

MODEL_PATH="${MODEL_PATH:-/media/ssd1/glm-5-nvfp4}"
HOST="${HOST:-0.0.0.0}"
PORT="${PORT:-30000}"

WINDOW_SECONDS="${WINDOW_SECONDS:-60}"
TRAINING_WINDOW_SECONDS="${TRAINING_WINDOW_SECONDS:-900}"
RETRAIN_INTERVAL_SECONDS="${RETRAIN_INTERVAL_SECONDS:-30}"
FUTURE_QPS_VALUES="${FUTURE_QPS_VALUES:-0.15,0.3,0.45,0.6,0.8,1.1,1.4}"
FUTURE_QPS_INTERVAL_SECONDS="${FUTURE_QPS_INTERVAL_SECONDS:-10}"
FUTURE_QPS_HORIZON_SECONDS="${FUTURE_QPS_HORIZON_SECONDS:-15}"
FUTURE_QPS_MATCH_TOLERANCE="${FUTURE_QPS_MATCH_TOLERANCE:-0.1}"

MEM_FRACTION_STATIC="${MEM_FRACTION_STATIC:-0.78}"
MAX_RUNNING_REQUESTS="${MAX_RUNNING_REQUESTS:-512}"
TP_SIZE="${TP_SIZE:-4}"
MAX_PREFILL_TOKENS="${MAX_PREFILL_TOKENS:-73728}"
CHUNKED_PREFILL_SIZE="${CHUNKED_PREFILL_SIZE:-16384}"
MAX_TOTAL_TOKENS="${MAX_TOTAL_TOKENS:-196608}"

RUN_TAG="${RUN_TAG:-ttft_online_$(date +%Y%m%d_%H%M%S)}"
ARTIFACT_BASE_DIR="${ARTIFACT_BASE_DIR:-${ROOT_DIR}/artifacts/ttft_online}"
ARTIFACT_DIR="${ARTIFACT_DIR:-${ARTIFACT_BASE_DIR}/${RUN_TAG}}"
METRICS_DIR="${METRICS_DIR:-${ARTIFACT_DIR}/metrics}"
PREDICTOR_DIR="${PREDICTOR_DIR:-${ARTIFACT_DIR}/predictor}"
MODEL_JSON_PATH="${MODEL_JSON_PATH:-${PREDICTOR_DIR}/sglang_window_ttft_model.json}"
EVENT_LOG_PATH="${EVENT_LOG_PATH:-${PREDICTOR_DIR}/sglang_window_ttft_events.jsonl}"
FUTURE_QPS_LOG_PATH="${FUTURE_QPS_LOG_PATH:-${PREDICTOR_DIR}/sglang_window_ttft_future_qps.jsonl}"

mkdir -p "${ARTIFACT_DIR}" "${METRICS_DIR}" "${PREDICTOR_DIR}"

export MODEL_PATH
export METRICS_DIR
export MEM_FRACTION_STATIC
export MAX_RUNNING_REQUESTS
export TP_SIZE
export MAX_PREFILL_TOKENS
export CHUNKED_PREFILL_SIZE
export MAX_TOTAL_TOKENS
export SGLANG_WINDOW_TTFT_PREDICTOR_WINDOW_SECONDS="${WINDOW_SECONDS}"
export SGLANG_WINDOW_TTFT_PREDICTOR_TRAINING_WINDOW_SECONDS="${TRAINING_WINDOW_SECONDS}"
export SGLANG_WINDOW_TTFT_PREDICTOR_RETRAIN_INTERVAL_SECONDS="${RETRAIN_INTERVAL_SECONDS}"
export SGLANG_WINDOW_TTFT_PREDICTOR_MODEL_PATH="${MODEL_JSON_PATH}"
export SGLANG_WINDOW_TTFT_PREDICTOR_EVENT_LOG_PATH="${EVENT_LOG_PATH}"
export SGLANG_WINDOW_TTFT_PREDICTOR_FUTURE_QPS_VALUES="${FUTURE_QPS_VALUES}"
export SGLANG_WINDOW_TTFT_PREDICTOR_FUTURE_QPS_INTERVAL_SECONDS="${FUTURE_QPS_INTERVAL_SECONDS}"
export SGLANG_WINDOW_TTFT_PREDICTOR_FUTURE_QPS_LOG_PATH="${FUTURE_QPS_LOG_PATH}"
export SGLANG_WINDOW_TTFT_PREDICTOR_FUTURE_QPS_HORIZON_SECONDS="${FUTURE_QPS_HORIZON_SECONDS}"
export SGLANG_WINDOW_TTFT_PREDICTOR_FUTURE_QPS_MATCH_TOLERANCE="${FUTURE_QPS_MATCH_TOLERANCE}"

echo "=== TTFT Online Server Launch ==="
echo "ROOT_DIR=${ROOT_DIR}"
echo "PYTHONPATH=${PYTHONPATH}"
echo "MODEL_PATH=${MODEL_PATH}"
echo "HOST=${HOST}"
echo "PORT=${PORT}"
echo "WINDOW_SECONDS=${WINDOW_SECONDS}"
echo "TRAINING_WINDOW_SECONDS=${TRAINING_WINDOW_SECONDS}"
echo "RETRAIN_INTERVAL_SECONDS=${RETRAIN_INTERVAL_SECONDS}"
echo "FUTURE_QPS_VALUES=${FUTURE_QPS_VALUES}"
echo "FUTURE_QPS_INTERVAL_SECONDS=${FUTURE_QPS_INTERVAL_SECONDS}"
echo "FUTURE_QPS_HORIZON_SECONDS=${FUTURE_QPS_HORIZON_SECONDS}"
echo "FUTURE_QPS_MATCH_TOLERANCE=${FUTURE_QPS_MATCH_TOLERANCE}"
echo "MEM_FRACTION_STATIC=${MEM_FRACTION_STATIC}"
echo "MAX_RUNNING_REQUESTS=${MAX_RUNNING_REQUESTS}"
echo "TP_SIZE=${TP_SIZE}"
echo "MAX_PREFILL_TOKENS=${MAX_PREFILL_TOKENS}"
echo "CHUNKED_PREFILL_SIZE=${CHUNKED_PREFILL_SIZE}"
echo "MAX_TOTAL_TOKENS=${MAX_TOTAL_TOKENS}"
echo "ARTIFACT_DIR=${ARTIFACT_DIR}"
echo "METRICS_DIR=${METRICS_DIR}"
echo "PREDICTOR_DIR=${PREDICTOR_DIR}"
echo "MODEL_JSON_PATH=${MODEL_JSON_PATH}"
echo "EVENT_LOG_PATH=${EVENT_LOG_PATH}"
echo "FUTURE_QPS_LOG_PATH=${FUTURE_QPS_LOG_PATH}"
echo
echo "Predictor status:"
echo "  GET  http://127.0.0.1:${PORT}/window_ttft_predictor_status"
echo "What-if qps:"
echo "  POST http://127.0.0.1:${PORT}/predict_window_ttft"
echo

exec bash "${ROOT_DIR}/scripts/launch_glm5_nvfp4.sh" --host "${HOST}" --port "${PORT}" "$@"
